name: caller_workflow

on:
    push:
        branches: [main]
    workflow_dispatch: 
        inputs:
            action: 
                type: choice
                required: true
                default: me
                options:
                    - me
                    - you

jobs:

    caller1:
        uses: ./.github/workflows/reusable-build.yml
        with:
            ubuntu_version: 'ubuntu-latest'

    caller2:
        needs: caller1
        env:
          OUTPUT_CALLER1: ${{needs.caller1.outputs.firstoutput}}
        runs-on: ubuntu-latest
        steps:
            - name: recuperation du output
              run: | 

                   echo "Affiche L'artifact"
                   echo "$OUTPUT_CALLER1" > artifact_fichier.txt
                
            - name: Artifact
              uses: actions/upload-artifact@v7
              with:
                name: Artifact_share
                path: artifact_fichier.txt

            
                       

                     