name: first

on:

    pull_request:
        branches: [main]
        types: [opened,synchronize]

permissions:
    contents: read

env:
    TEST_SECRET: ${{secrets.TEST_SECRET}}

jobs:
    learn:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout du code
              uses: actions/checkout@fbc6f3992d24b796d5a048ff273f7fcc4a7b6c09 #v5

            - name: check checkout
              run: |

                    echo "On check le repo"
                    ls -ltrh
            - name: Contexte du lancement du pipeline
              run: |

                     echo "Nom du repo ${{github.repository}}\n"
                     echo "Nom de l'event qui declanche le pipeline ${{github.event_name}}"
                     echo "Nom du user qui declanche le workflow ${{github.actor}}"
                     echo "Nom de la branche ou le workflow est lance ${{github.ref_name}}"

            - name: Afficher le Secret
              run: |

                     if [${#TEST_SECRET} -gt 0]; then
                        echo "La valeur est $TEST_SECRET"
                     else 
                        echo "La variable TEST_SECRET est vide"
                     fi 
                       
