name: first

on:

    pull_request:
        branches: [main]
        types: [opened,synchronize]

permissions:
    contents: read


jobs:
    learn:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout du code
              uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 #v7.0.1

            - name: check checkout
              run: |

                    echo "On check le repo"
                    ls -ltrh
            - name: Contexte du lancement du pipeline
              run: |

                     echo "Nom du repo ${{github.repository}}"
                     echo "Nom de l'event qui declanche le pipeline ${{github.event_name}}"
                     echo "Nom du user qui declanche le workflow ${{github.actor}}"
                     echo "Nom de la branche ou le workflow est lance ${{github.ref_name}}"

            - name: Check Secret
              env:
                TEST_SECRET: ${{secrets.TEST_SECRET}}
              
              run: |

                     if [ -n "$TEST_SECRET" ]; then
                        echo "Le secrets est non vide"
                     else
                        echo "Le secret est vide"
                     fi


                       
