name: reusable

on:
    workflow_call: 
        inputs:
            msg_artifact:
                required: true
                type: string

        outputs:
            firstoutput:
                description: "Output pour le reusable workflow"
                value: ${{jobs.update.outputs.output1}}


                


permissions:
    contents: read

jobs:
    update:
        runs-on: ubuntu-latest
        outputs:
            output1: ${{steps.file_id.outputs.msg}}
        steps:

            - name: Version du os
              run: |

                     echo "hello world"
                     cat /etc/os-release

            - name: Creation de l'artifact
              id: file_id

              env:
                ARTIFACT: ${{inputs.msg_artifact}}
              run: |
                    echo "msg=$ARTIFACT" >> "$GITHUB_OUTPUT"
                    echo "$ARTIFACT" >> file.txt
            
            - name: Artifact Upload
              uses: actions/upload-artifact@v7
              with:
                name: upload_artifact
                path: file.txt
            


         