name: review-jour1-3

on:
    push:
        branches: [main]
    pull_request: 
        branches: [main,tes-branch]
        types: [opened,reopened,synchronize]
    workflow_dispatch: 
        inputs:
            action:
                type: choice
                description: "Un choix est necessaire"
                required: true
                default: plan
                options:
                    - plan
                    - apply
                    - destroy


permissions:
    contents: read

jobs:
    prepare:
        if: (github.event_name == 'push' || github.event_name == 'pull_request' || github.event.inputs.action == 'plan')
        outputs:
            outputs_job: ${{steps.version_id.outputs.version}}
        runs-on: ubuntu-latest
        steps:
            - name: Checkout du code 
              uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 #v7
              with:
                persist-credentials: false
            
            - name: Definition du cache
              id: cache_id
              uses: actions/cache@caa296126883cff596d87d8935842f9db880ef25 # v5
              with:
                path: '**/truth-file.txt'
                key: truth-file-${{runner.os}}-${{hashFiles('**/truth-file.txt')}}
                restore-keys: |
                               truth-file-${{runner.os}}-
                               truth-file-
            
            - name: Status du cache
              if: steps.cache_id.outputs.cache-hit != 'true'
              run: |
                     echo  "Echec du cache-hit: $(date)"

            - name: Contexte du workflow
              env:
                 EVENT_TRIGGER: ${{github.event_name}}
                 HEAD_REF: ${{ github.head_ref }}
                 REPOSITORY: ${{ github.repository }}
                 ACTOR: ${{ github.actor }}
              run: |

                     echo "Nom du reporitory: ${REPOSITORY}"
                     echo "Nom de celui qui delanche le workflow: ${ACTOR}"
                     if [ "${EVENT_TRIGGER}" == 'push' ]; then
                        echo "Le nom du event trigger: ${EVENT_TRIGGER}"
                     elif [ "${EVENT_TRIGGER}" == 'pull_request' ]; then
                        echo "Le nom du event trigger: ${HEAD_REF}"
                     else
                         echo "Le nom du event trigger : ${EVENT_TRIGGER}"
                     fi
            - name: Outputs de job
              id: version_id
              run: |
                     echo "version=v:$(date)" >> "$GITHUB_OUTPUT"
            - name: Creation du artifact
              run: |

                    mkdir -p artifact-folder && cd artifact-folder
                    echo "Hello je suis l' artifact a partage" >> file.txt

            - name: Upload de l'artifact
              uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
              with:
                name: Artifact-Shared
                path: artifact-folder/file.txt
                retention-days: 1
            
    
    build:
        needs: [prepare]
        runs-on: ubuntu-latest
        steps:
            - name: Afficher le output
              run: |
                    echo "Le output: ${{needs.prepare.outputs.outputs_job}}"

            - name: Download d l'artifact
              uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7
              with:
                name: Artifact-Shared
                path: dest-artifact

            - name: Check de l'artefact
              run: |
            
                    cat dest-artifact/file.txt

            - name: Afficher le résumé
              run: |
                      echo "Valeur du output1 du job prepare"
                      echo "La valeur est : ${{ needs.prepare.outputs.outputs_job }}"

                      cat <<EOF >> "$GITHUB_STEP_SUMMARY"
                      ## 📦 Artifact obtenu

                      Voici l'artifact obtenu :

                      - **Nom :** \`Artifact-Shared\`
                      - **Fichier :** \`file.txt\`
                      - **Statut :** ✅ Généré avec succès

                      ## 📋 Résultat du job prepare

                      **Output1 :** \`${{ needs.prepare.outputs.outputs_job }}\`
                      EOF
        

              
                         
                                
            
            
